application:
  telegram:
    token: ${TELEGRAM_TOKEN}
    username: ${TELEGRAM_USERNAME}
server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 128MB
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true